import type {StickerListItem, User} from '../types';
import { StickerForm } from '../pages/stickers/create-prototype/enum.ts';

const stickersList: StickerListItem[] = [
    {
        id: 1,
        title: 'Title Company',
        highlightedText: 'Super text',
        promo: 'Discount 20%',
        qrCodeLink: 'https://google.com',
        address: 'Address 1117, 7',
        phone: '+1456 36 23',
        titleColor: '#111111',
        highlightedBgColor: '#111111',
        stickerForm: StickerForm.rectangle,
    },
    {
        id: 2,
        title: 'Title Company 2',
        highlightedText: 'Super text',
        promo: 'Discount 20%',
        qrCodeLink: 'https://google.com',
        address: 'Address 1117, 7',
        phone: '+1456 36 23',
        titleColor: '#111111',
        highlightedBgColor: '#111111',
        stickerForm: StickerForm.rectangle,
    },
    {
        id: 3,
        title: 'Title Company 3',
        highlightedText: 'Super text',
        promo: 'Discount 20%',
        qrCodeLink: 'https://google.com',
        address: 'Address 1117, 7',
        phone: '+1456 36 23',
        titleColor: '#111111',
        highlightedBgColor: '#111111',
        stickerForm: StickerForm.rectangle,
    },
    {
        id: 4,
        title: 'Title Company 4',
        highlightedText: 'Super text',
        promo: 'Discount 20%',
        qrCodeLink: 'https://google.com',
        address: 'Address 1117, 7',
        phone: '+1456 36 23',
        titleColor: '#111111',
        highlightedBgColor: '#111111',
        stickerForm: StickerForm.rectangle,
    },
    {
        id: 5,
        title: 'Title Company 5',
        highlightedText: 'Super text',
        promo: 'Discount 20%',
        qrCodeLink: 'https://google.com',
        address: 'Address 1117, 7',
        phone: '+1456 36 23',
        titleColor: '#111111',
        highlightedBgColor: '#111111',
        stickerForm: StickerForm.rectangle,
    },
];

export const DemoUser: User = {
    id: 1,
    name: 'Demo',
    stickersList,
}
